import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Image from "next/image";

export const metadata = {
  title: "Aris Stogiannos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body  className='overflow-x-hidden   bg-mblack '>
        {children}
        {/* <Image src={"/Frame 8.png"} width={1920} height={1080} unoptimized={true} className="fixed top-0 left-0 -z-[2000] h-screen "/> */}
      <SpeedInsights/>
     
        </body>
    </html>
  );
}
