import "./globals.css";


export const metadata = {
  title: "Aris Stogiannos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body  className='overflow-x-hidden bg-mblack '>
        {children}
        </body>
    </html>
  );
}
